name: Automated Comment On A Newly Created Issue

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: Comment On A Newly Opened Issue
      - uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for spotting out and creating an issue
          reactions: "+1"
